// <auto-generated />
using System;
using MTWireGuard.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTWireGuard.Application.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240716184029_RemoveUnnecessaryUserFields")]
    partial class RemoveUnnecessaryUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MTWireGuard.Application.Models.DataUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RX")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResetNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("TX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserReset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataUsages");
                });

            modelBuilder.Entity("MTWireGuard.Application.Models.LastKnownTraffic", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TX")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("LastKnownTraffic");
                });

            modelBuilder.Entity("MTWireGuard.Application.Models.Mikrotik.WGPeerDBModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpireID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritDNS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritIP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrafficLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MTWireGuard.Application.Models.Mikrotik.WGServerDBModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DNSAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IPPoolId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InheritDNS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseIPPool")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
